# -*- coding: utf-8 -*-
"""❤️

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VJO0533AeUVsi4zigDf_T0boy_ZN34NH

#Mapa de Paranapiacaba

Clima: 
Tropical úmido

Cidades Limítrofes:
Norte - Mogi das Cruzes
Sul - Santos
Leste - Mogi das Cruzes e Santos
Oeste - Cubatão

latitude =  -23.7787869
    longitude = -46.3053042
    zoom = 16
"""

import folium
import pandas as pd

"""Deve-se utilizar objeto tipo Map, neste objeto é preciso colocar a localização da cidade escolhida."""

mapa = folium.Map(location=[-23.7787869, -46.3053042], 
                           zoom_start=16)

mapa

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("Arthur.csv", sep=";", decimal=',') #Chamando pelo nome o arquivo: dataset
df.head() #ler

# Primeiro criamos o objeto m para o mapa
m = folium.Map(location=[-23.7787869, -46.3053042], zoom_start=22)# Depois adicionamos o marcador. 
folium.Marker(location=[-23.7792374,-46.3030168], 
              popup='Museu ferroviário',
              icon=folium.Icon(color='pink', icon='info-sign')
).add_to(m)
folium.Marker(location=[-23.7785842,-46.3042809], 
              popup=' Paróquia Senhor Bom Jesus de Paranapiacaba (1889) ',
              icon=folium.Icon(color='pink', icon='info-sign')
).add_to(m)
m

folium.Marker(location=[-23.7780618,-46.3007407], 
              popup='Museu castelinho',
              icon=folium.Icon(color='pink', icon='info-sign')
).add_to(m)
m
folium.Marker(location=[-23.7764676,-46.3034215], 
              popup='Relogio',
              icon=folium.Icon(color='pink', icon='info-sign')
).add_to(m)
m

folium.Marker(location=[-23.7775811,-46.3001971], 
              popup='Mercado central',
              icon=folium.Icon(color='pink', icon='info-sign')
).add_to(m)
m
folium.Marker(location=[-23.7771859,-46.3013796], 
              popup='Nascentes',
              icon=folium.Icon(color='pink', icon='info-sign')
).add_to(m)
m
folium.Marker(location=[-23.7779228,-46.3029487], 
              popup='Ponte',
              icon=folium.Icon(color='pink', icon='info-sign')
).add_to(m)
m
folium.Marker(location=[-23.7769444,-46.2983333], 
              popup='Hotel Os memorialistas',
              icon=folium.Icon(color='pink', icon='info-sign')
).add_to(m)
m
folium.Marker(location=[-23.7782795,-46.2998846], 
              popup='Associação de bruxas',
              icon=folium.Icon(color='pink', icon='info-sign')
).add_to(m)
m
folium.Marker(location=[-23.7766636,-46.3011617], 
              popup='Casa Fox',
              icon=folium.Icon(color='pink', icon='info-sign')
).add_to(m)
m
folium.Marker(location=[-23.778473,-46.299892], 
              popup='Biblioteca',
              icon=folium.Icon(color='pink', icon='info-sign')
).add_to(m)
m
folium.CircleMarker(
    location=[-23.7769444,-46.2983333],
    radius=50,
    popup='Amor',
    color='blue',
    fill=True,
    fill_color='lightblue'
).add_to(m)
m
